export const SLOT_GAMES = [
  { id: 'classic', title: 'Classic 777', color: '#e63946', desc: 'The original Vegas experience.' },
  { id: 'neon', title: 'Neon Fruits', color: '#a855f7', desc: 'Cyberpunk style fruit spins.' },
  { id: 'pharaoh', title: 'Pharaoh\'s Gold', color: '#facc15', desc: 'Ancient riches await.' },
  { id: 'pirate', title: 'Pirate\'s Booty', color: '#8B4513', desc: 'Plunder the high seas.' },
  { id: 'alien', title: 'Alien Invasion', color: '#22c55e', desc: 'Extraterrestrial encounters.' },
  { id: 'ocean', title: 'Deep Ocean', color: '#3b82f6', desc: 'Dive into underwater treasures.' },
  { id: 'candy', title: 'Sugar Rush', color: '#ec4899', desc: 'Sweet treats and big wins.' },
  { id: 'viking', title: 'Valhalla Wins', color: '#94a3b8', desc: 'Conquer the icy north.' },
  { id: 'ninja', title: 'Shadow Shinobi', color: '#475569', desc: 'Silent strikes, massive payouts.' },
  { id: 'western', title: 'Wild West', color: '#f97316', desc: 'Saddle up for the gold rush.' },
  { id: 'crypto', title: 'Crypto Moon', color: '#06b6d4', desc: 'To the moon! HODL for jackpots.' },
  { id: 'magic', title: 'Wizard\'s Spell', color: '#d946ef', desc: 'Magical multipliers.' },
  { id: 'nature', title: 'Enchanted Forest', color: '#84cc16', desc: 'Mystical creatures and flora.' },
  { id: 'zombie', title: 'Zombie Survival', color: '#65a30d', desc: 'Survive the apocalypse.' },
  { id: 'mafia', title: 'Mobster\'s Cut', color: '#1e293b', desc: 'Take over the underground.' },
  { id: 'space', title: 'Galactic Empire', color: '#1d4ed8', desc: 'Explore the infinite cosmos.' },
];

export const THEME_SYMBOLS = {
  classic: [
    { id: 'cherry', char: '🍒', label: 'Cherry', payout3: 3, payout2: 1 },
    { id: 'lemon', char: '🍋', label: 'Lemon', payout3: 5, payout2: 1.5 },
    { id: 'orange', char: '🍊', label: 'Orange', payout3: 8, payout2: 2 },
    { id: 'grape', char: '🍇', label: 'Grape', payout3: 12, payout2: 0 },
    { id: 'bell', char: '🔔', label: 'Bell', payout3: 20, payout2: 0 },
    { id: 'seven', char: '7️⃣', label: 'Lucky 7', payout3: 35, payout2: 0 },
    { id: 'diamond', char: '💎', label: 'Diamond', payout3: 75, payout2: 0 },
    { id: 'crown', char: '👑', label: 'Crown', payout3: 200, payout2: 0 },
  ],
  neon: [
    { id: 'apple', char: '🍏', label: 'Neon Apple', payout3: 4, payout2: 1 },
    { id: 'kiwi', char: '🥝', label: 'Cyber Kiwi', payout3: 6, payout2: 1.5 },
    { id: 'melon', char: '🍉', label: 'Synth Melon', payout3: 10, payout2: 2 },
    { id: 'star', char: '⭐', label: 'Star', payout3: 15, payout2: 0 },
    { id: 'zap', char: '⚡', label: 'Energy', payout3: 25, payout2: 0 },
    { id: 'alien', char: '👾', label: 'Invader', payout3: 50, payout2: 0 },
    { id: 'rocket', char: '🚀', label: 'Rocket', payout3: 100, payout2: 0 },
    { id: 'gem', char: '🔮', label: 'Plasma Gem', payout3: 300, payout2: 0 },
  ],
  pharaoh: [
    { id: 'sand', char: '🏜️', label: 'Dunes', payout3: 3, payout2: 1 },
    { id: 'camel', char: '🐪', label: 'Camel', payout3: 5, payout2: 1.5 },
    { id: 'snake', char: '🐍', label: 'Cobra', payout3: 10, payout2: 2 },
    { id: 'eye', char: '👁️', label: 'Eye of Ra', payout3: 18, payout2: 0 },
    { id: 'ankh', char: '🪬', label: 'Ankh', payout3: 30, payout2: 0 },
    { id: 'scarab', char: '🪲', label: 'Scarab', payout3: 60, payout2: 0 },
    { id: 'pyramid', char: '🛕', label: 'Pyramid', payout3: 120, payout2: 0 },
    { id: 'pharaoh', char: '🗿', label: 'Pharaoh', payout3: 250, payout2: 0 },
  ],
  pirate: [
    { id: 'hook', char: '🪝', label: 'Hook', payout3: 3, payout2: 1 },
    { id: 'anchor', char: '⚓', label: 'Anchor', payout3: 5, payout2: 1.5 },
    { id: 'wheel', char: '☸️', label: 'Wheel', payout3: 10, payout2: 2 },
    { id: 'map', char: '🗺️', label: 'Map', payout3: 18, payout2: 0 },
    { id: 'sword', char: '⚔️', label: 'Swords', payout3: 30, payout2: 0 },
    { id: 'bomb', char: '💣', label: 'Bomb', payout3: 60, payout2: 0 },
    { id: 'chest', char: '🏴‍☠️', label: 'Jolly Roger', payout3: 120, payout2: 0 },
    { id: 'gold', char: '💰', label: 'Treasure', payout3: 250, payout2: 0 },
  ],
  alien: [
    { id: 'crater', char: '🕳️', label: 'Crater', payout3: 3, payout2: 1 },
    { id: 'comet', char: '☄️', label: 'Comet', payout3: 5, payout2: 1.5 },
    { id: 'moon', char: '🌕', label: 'Moon', payout3: 10, payout2: 2 },
    { id: 'saturn', char: '🪐', label: 'Saturn', payout3: 18, payout2: 0 },
    { id: 'dna', char: '🧬', label: 'Alien DNA', payout3: 30, payout2: 0 },
    { id: 'saucer', char: '🛸', label: 'UFO', payout3: 60, payout2: 0 },
    { id: 'alien2', char: '👽', label: 'Martian', payout3: 120, payout2: 0 },
    { id: 'brain', char: '🧠', label: 'Mastermind', payout3: 250, payout2: 0 },
  ],
  ocean: [
    { id: 'shell', char: '🐚', label: 'Shell', payout3: 3, payout2: 1 },
    { id: 'fish', char: '🐟', label: 'Fish', payout3: 5, payout2: 1.5 },
    { id: 'crab', char: '🦀', label: 'Crab', payout3: 10, payout2: 2 },
    { id: 'turtle', char: '🐢', label: 'Turtle', payout3: 18, payout2: 0 },
    { id: 'dolphin', char: '🐬', label: 'Dolphin', payout3: 30, payout2: 0 },
    { id: 'shark', char: '🦈', label: 'Shark', payout3: 60, payout2: 0 },
    { id: 'octopus', char: '🐙', label: 'Kraken', payout3: 120, payout2: 0 },
    { id: 'trident', char: '🔱', label: 'Trident', payout3: 250, payout2: 0 },
  ],
  candy: [
    { id: 'donut', char: '🍩', label: 'Donut', payout3: 3, payout2: 1 },
    { id: 'cookie', char: '🍪', label: 'Cookie', payout3: 5, payout2: 1.5 },
    { id: 'candy', char: '🍬', label: 'Candy', payout3: 10, payout2: 2 },
    { id: 'choco', char: '🍫', label: 'Chocolate', payout3: 18, payout2: 0 },
    { id: 'cake', char: '🍰', label: 'Cake', payout3: 30, payout2: 0 },
    { id: 'icecream', char: '🍦', label: 'Ice Cream', payout3: 60, payout2: 0 },
    { id: 'loli', char: '🍭', label: 'Lollipop', payout3: 120, payout2: 0 },
    { id: 'crown', char: '👑', label: 'Sugar King', payout3: 250, payout2: 0 },
  ],
  viking: [
    { id: 'snow', char: '❄️', label: 'Snowflake', payout3: 3, payout2: 1 },
    { id: 'meat', char: '🍖', label: 'Meat', payout3: 5, payout2: 1.5 },
    { id: 'beer', char: '🍺', label: 'Mead', payout3: 10, payout2: 2 },
    { id: 'shield', char: '🛡️', label: 'Shield', payout3: 18, payout2: 0 },
    { id: 'axe', char: '🪓', label: 'Axe', payout3: 30, payout2: 0 },
    { id: 'boat', char: '🛶', label: 'Longship', payout3: 60, payout2: 0 },
    { id: 'wolf', char: '🐺', label: 'Fenrir', payout3: 120, payout2: 0 },
    { id: 'valhalla', char: '🏰', label: 'Valhalla', payout3: 250, payout2: 0 },
  ],
  ninja: [
    { id: 'leaf', char: '🍃', label: 'Leaf', payout3: 3, payout2: 1 },
    { id: 'scroll', char: '📜', label: 'Scroll', payout3: 5, payout2: 1.5 },
    { id: 'shuriken', char: '🥷', label: 'Ninja', payout3: 10, payout2: 2 },
    { id: 'knife', char: '🗡️', label: 'Kunai', payout3: 18, payout2: 0 },
    { id: 'mask', char: '👺', label: 'Tengu', payout3: 30, payout2: 0 },
    { id: 'dragon', char: '🐉', label: 'Dragon', payout3: 60, payout2: 0 },
    { id: 'moon', char: '🌒', label: 'Blood Moon', payout3: 120, payout2: 0 },
    { id: 'temple', char: '⛩️', label: 'Dojo', payout3: 250, payout2: 0 },
  ],
  western: [
    { id: 'cactus', char: '🌵', label: 'Cactus', payout3: 3, payout2: 1 },
    { id: 'boot', char: '👢', label: 'Boot', payout3: 5, payout2: 1.5 },
    { id: 'hat', char: '🤠', label: 'Cowboy', payout3: 10, payout2: 2 },
    { id: 'horse', char: '🐴', label: 'Mustang', payout3: 18, payout2: 0 },
    { id: 'gun', char: '🔫', label: 'Revolver', payout3: 30, payout2: 0 },
    { id: 'badge', char: '⭐', label: 'Sheriff', payout3: 60, payout2: 0 },
    { id: 'bag', char: '💰', label: 'Loot', payout3: 120, payout2: 0 },
    { id: 'train', char: '🚂', label: 'Gold Train', payout3: 250, payout2: 0 },
  ],
  crypto: [
    { id: 'coin', char: '🪙', label: 'Coin', payout3: 3, payout2: 1 },
    { id: 'chart', char: '📉', label: 'Dip', payout3: 5, payout2: 1.5 },
    { id: 'up', char: '📈', label: 'Pump', payout3: 10, payout2: 2 },
    { id: 'diamond', char: '💎', label: 'Diamond Hands', payout3: 18, payout2: 0 },
    { id: 'rocket', char: '🚀', label: 'To The Moon', payout3: 30, payout2: 0 },
    { id: 'pc', char: '💻', label: 'Miner', payout3: 60, payout2: 0 },
    { id: 'whale', char: '🐋', label: 'Whale', payout3: 120, payout2: 0 },
    { id: 'btc', char: '₿', label: 'Bitcoin', payout3: 250, payout2: 0 },
  ],
  magic: [
    { id: 'potion', char: '🧪', label: 'Potion', payout3: 3, payout2: 1 },
    { id: 'book', char: '📖', label: 'Grimoire', payout3: 5, payout2: 1.5 },
    { id: 'wand', char: '🪄', label: 'Wand', payout3: 10, payout2: 2 },
    { id: 'hat', char: '🧙', label: 'Wizard', payout3: 18, payout2: 0 },
    { id: 'crystal', char: '🔮', label: 'Orb', payout3: 30, payout2: 0 },
    { id: 'owl', char: '🦉', label: 'Familiar', payout3: 60, payout2: 0 },
    { id: 'dragon', char: '🐲', label: 'Wyrm', payout3: 120, payout2: 0 },
    { id: 'staff', char: '🧿', label: 'Elder Staff', payout3: 250, payout2: 0 },
  ],
  nature: [
    { id: 'leaf', char: '🍀', label: 'Clover', payout3: 3, payout2: 1 },
    { id: 'flower', char: '🌸', label: 'Lotus', payout3: 5, payout2: 1.5 },
    { id: 'tree', char: '🌳', label: 'Oak', payout3: 10, payout2: 2 },
    { id: 'bug', char: '🦋', label: 'Butterfly', payout3: 18, payout2: 0 },
    { id: 'fox', char: '🦊', label: 'Fox', payout3: 30, payout2: 0 },
    { id: 'deer', char: '🦌', label: 'Stag', payout3: 60, payout2: 0 },
    { id: 'bear', char: '🐻', label: 'Grizzly', payout3: 120, payout2: 0 },
    { id: 'spirit', char: '🧚', label: 'Forest Spirit', payout3: 250, payout2: 0 },
  ],
  zombie: [
    { id: 'bone', char: '🦴', label: 'Bone', payout3: 3, payout2: 1 },
    { id: 'blood', char: '🩸', label: 'Blood', payout3: 5, payout2: 1.5 },
    { id: 'brain', char: '🧠', label: 'Brain', payout3: 10, payout2: 2 },
    { id: 'bat', char: '🦇', label: 'Bat', payout3: 18, payout2: 0 },
    { id: 'zombie', char: '🧟', label: 'Walker', payout3: 30, payout2: 0 },
    { id: 'gun', char: '🔫', label: 'Shotgun', payout3: 60, payout2: 0 },
    { id: 'bio', char: '☣️', label: 'Hazard', payout3: 120, payout2: 0 },
    { id: 'cure', char: '💉', label: 'The Cure', payout3: 250, payout2: 0 },
  ],
  mafia: [
    { id: 'cigar', char: '🚬', label: 'Cigar', payout3: 3, payout2: 1 },
    { id: 'card', char: '🃏', label: 'Joker', payout3: 5, payout2: 1.5 },
    { id: 'dice', char: '🎲', label: 'Dice', payout3: 10, payout2: 2 },
    { id: 'money', char: '💵', label: 'Cash', payout3: 18, payout2: 0 },
    { id: 'gun', char: '🔫', label: 'Tommy Gun', payout3: 30, payout2: 0 },
    { id: 'car', char: '🚗', label: 'Getaway', payout3: 60, payout2: 0 },
    { id: 'boss', char: '🕴️', label: 'Don', payout3: 120, payout2: 0 },
    { id: 'vault', char: '🏦', label: 'The Bank', payout3: 250, payout2: 0 },
  ],
  space: [
    { id: 'star', char: '✨', label: 'Star', payout3: 3, payout2: 1 },
    { id: 'comet', char: '☄️', label: 'Meteor', payout3: 5, payout2: 1.5 },
    { id: 'earth', char: '🌍', label: 'Earth', payout3: 10, payout2: 2 },
    { id: 'sun', char: '☀️', label: 'Sun', payout3: 18, payout2: 0 },
    { id: 'astro', char: '🧑‍🚀', label: 'Astronaut', payout3: 30, payout2: 0 },
    { id: 'ship', char: '🚀', label: 'Spaceship', payout3: 60, payout2: 0 },
    { id: 'galaxy', char: '🌌', label: 'Nebula', payout3: 120, payout2: 0 },
    { id: 'blackhole',char: '🕳️', label: 'Singularity', payout3: 250, payout2: 0 },
  ]
};
